"""empty message

Revision ID: 31928ca374eb
Revises: 9f945b187333
Create Date: 2024-11-13 23:04:22.933095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31928ca374eb'
down_revision = '9f945b187333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similar_news', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('similar_news')

    # ### end Alembic commands ###
