"""empty message

Revision ID: 554bb9dd348d
Revises: d2d7462c1b0d
Create Date: 2024-11-15 16:54:32.251297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554bb9dd348d'
down_revision = 'd2d7462c1b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('news_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=300),
               existing_nullable=True)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('news_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=300),
               existing_nullable=False)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=300),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('news_id_seq'::regclass)"))

    with op.batch_alter_table('saved_news', schema=None) as batch_op:
        batch_op.alter_column('news_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_news', schema=None) as batch_op:
        batch_op.alter_column('news_id',
               existing_type=sa.String(length=300),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=300),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('news_id_seq'::regclass)"))

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('news_id',
               existing_type=sa.String(length=300),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('news_id',
               existing_type=sa.String(length=300),
               type_=sa.BIGINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
