"""empty message

Revision ID: cdf92c7b7601
Revises: 51cf6a0b37e3
Create Date: 2024-11-25 19:46:27.583696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf92c7b7601'
down_revision = '51cf6a0b37e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_news_id_fkey', type_='foreignkey')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_news_id_fkey', type_='foreignkey')

    with op.batch_alter_table('saved_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(length=300), nullable=True))
        batch_op.drop_constraint('saved_news_news_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_news', schema=None) as batch_op:
        batch_op.create_foreign_key('saved_news_news_id_fkey', 'news', ['news_id'], ['id'])
        batch_op.drop_column('img_url')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_foreign_key('likes_news_id_fkey', 'news', ['news_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_foreign_key('comments_news_id_fkey', 'news', ['news_id'], ['id'])

    # ### end Alembic commands ###
